name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y maven
        
    - name: Generate tests
      run: python test_generator.py
      
    - name: Run Karate tests
      run: |
        mvn test -Dtest=KarateRunner -B
      
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/karate-reports/