# .github/workflows/tests.yml
name: Unit and Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: pytest tests/unit -v
        
      - name: Run Integration Tests
        run: pytest tests/integration -v
        
      - name: Security Scan
        run: pytest tests/security -v